### ISSUE TITLE
v2.2.2 still referencing IDFA

### ISSUE THREAD

**Issue by shochet** [mixpanel/mixpanel-unity#111]
FYI - Looks like Controller.cs is still calling 

`properties["$ios_ifa"] = Device.advertisingIdentifier;
`

inside GetEventsDefaultProperties()
v2.2.1 removed the line from GetEngageDefaultProperties but left this reference in accidentally?
This is easy to work around by commenting out the line.

**Comment by zihejia** [comment]
hi @shochet , this has been removed in v2.2.3. Thanks for bringing it up.
