### ISSUE TITLE
Mixpanel Controller DontDestroyOnLoad Flag 

### ISSUE THREAD

**Issue by wiurxee** [mixpanel/mixpanel-unity#124]
Hi,
After upgrading from v2.1.4 to v3.0.1 I noticed that there is a change in the code that instantiates the mixpanel controller, now the mixpanel gameobject is not marked with DontDestroyOnLoad flag, so when changing between scenes the object might be destroyed.

**Comment by zihejia** [comment]
hi @wiurxee , we have released v3.0.2 which should fix this issue. Thanks for bringing it up.
