### ISSUE TITLE
Mixing mixpanel ?  iOS + Unity mixpanel client crash

### ISSUE THREAD

**Issue by Zornikachu** [mixpanel/mixpanel-unity#13]
Hello there,

My project is a bit complex and here is how it works : 

This is a iOS project with the mixpanel pods installed and using tracking of events, everything works fine so far.

Now inside the iOS app we launch a Unity client, with mixpanel-unity inside the main scene.
Everything works fine as I have setted the same token key to both mixpanels API.

But when I stopped the unity client and launch it again I always get the same error : 
Mixpanel unity Side bug and the app crash : here are the log, maybe it is something really simple but I can't do anything.

<img width="1267" alt="capture d ecran 2016-08-18 a 00 24 01" src="https://cloud.githubusercontent.com/assets/12764027/17755430/37a87bb4-64da-11e6-8e47-18f176a94efc.png">

Anyway I'm stuck here =/

**Comment by Zornikachu** [comment]
Allright I worked around this problem by sending every tracking and infos i need to iOS, informations that are then handled by iOS mixpanel.

So we can close this thing

**Comment by bigjhnny** [comment]
The way Mixpanel class was written is that the game object persists over reloads as it has a "DontDestroyOnLoad(this);" in the Awake function.

We got around the crash by not instantiating another mixpanel gameobject.

**Comment by zihejia** [comment]
Thanks @bigjhnny. We will close this one for now.
