### ISSUE TITLE
App build code and version name are inverted when registering the super properties in Android

### ISSUE THREAD

**Issue by argenisf** [mixpanel/mixpanel-unity#14]
When registering $app_version_string and $app_build_number, the SDK is doing so with the values inverted, as can be seen here:

https://github.com/mixpanel/mixpanel-unity/blob/8c0f7a8e9c305f1ee26ea3b4890efbfbb0850f39/deployments/UnityMixpanel/Assets/Mixpanel/Mixpanel.cs#L594

Just switching the value assigned to the 2 properties (as they are in the People update below that) would solve the problem.

Pull request: https://github.com/mixpanel/mixpanel-unity/pull/15

**Comment by patedit** [comment]
Thanks @argenisf for the PR :) It has been merged!
