### ISSUE TITLE
LICENSE has no meta file

### ISSUE THREAD

**Issue by starikcetin** [mixpanel/mixpanel-unity#147]
Please generate a meta file for the LICENSE file to get rid of this error:
`Asset Packages/com.mixpanel.unity/LICENSE has no meta file, but it's in an immutable folder. The asset will be ignored.`

**Comment by Ale1** [comment]
Hi, @jaredmixpanel; could this be addressed?  
Its highly disruptive to our workflow for this package to spam us with error messages while working in editor.  The fix is literally a 1-liner.  Happy to PR it if needed.

**Comment by zihejia** [comment]
hi @Ale1 , I've added the missing file to the master, sorry about the inconvenience.

**Comment by starikcetin** [comment]
@zihejia Could you publish a new patch version so we can consume it?

**Comment by zihejia** [comment]
Sure, https://github.com/mixpanel/mixpanel-unity/releases/tag/v3.3.1
