### ISSUE TITLE
Unresolved and unexplained bug in timed events $duration property

### ISSUE THREAD

**Issue by martins-jansevskis** [mixpanel/mixpanel-unity#149]
The commit: https://github.com/mixpanel/mixpanel-unity/pull/146

The mixpanel documentation are describing that $duration is in 'seconds' for every timed event int Unity, Android and iOS SDKs. 
The '$duration' property in 3.3.1 Unity is a timestamp in milliseconds and seconds from other SDKs and older Unity SDK versions.

The clients who have production applications with some users on 3.0.1 and others in 3.3.1 have corrupt '$duration' data.

**Comment by argenisf** [comment]
hey @martins-jansevskis , just reached out to you in the support ticket. Mind following up there? It looks like $duration should still be in seconds (even if the timestamp of the event itself has millisecond precision): https://github.com/mixpanel/mixpanel-android/blob/153674249b3f588dcb597318d850a76460e7725a/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L800

**Comment by martins-jansevskis** [comment]
The following two lines of code are in milliseconds and not seconds:
* https://github.com/mixpanel/mixpanel-unity/blob/6c4b020c787d6a128d07ac51f0ea9d852bb09928/Mixpanel/Worker.cs#L20
* https://github.com/mixpanel/mixpanel-unity/blob/6c4b020c787d6a128d07ac51f0ea9d852bb09928/Mixpanel/Controller.cs#L354

**Comment by argenisf** [comment]
You are correct, the reference I had above was a confusion I had with the Android library. I will create an internal bug report and review it with the engineering team.

**Comment by jaredmixpanel** [comment]
@martins-jansevskis @argenisf thanks for the report. this issue should be fixed in `v3.3.2`. feel free to re-open if any problems persist.
