### ISSUE TITLE
Mixpanel stops tracking events after a while for most users

### ISSUE THREAD

**Issue by mschneider** [mixpanel/mixpanel-unity#16]
We migrated our app from the native iOS SDK to the Unity SDK.
Somehow our app installations stop sending events after manually killing the app once.

Any thought's why this might happen and what we can do to troubleshoot this issue?
Can we enable debugging output like in the native SDK?

**Comment by Acimaz** [comment]
@mschneider Hey, is this still happening? Our company is going to use the sdk as well, but if the project is not developed anymore i might switch to something else i think. You comment is now 29 days old and noone has written a respond.

**Comment by zihejia** [comment]
Sorry it's been a while... This issue might relate to the issue (https://github.com/mixpanel/mixpanel-unity/issues/44), we have released a new version v1.2.0 with a fix to this problem, please try again and feel free to reopen it if the same problem still exists.
