### ISSUE TITLE
New file release.py has no meta file

### ISSUE THREAD

**Issue by yingxuel** [mixpanel/mixpanel-unity#164]
Unity complaining that the newly added release.py has no meta file and is in immutable folder.

<img width="781" alt="Screenshot 2023-09-26 at 4 18 26 PM" src="https://github.com/mixpanel/mixpanel-unity/assets/2745855/18034764-70bf-4d27-add1-ef4b5c5849bd">

**Comment by katylinn** [comment]
+1. Please fix.

I was able to get temporarily unblocked by manually deleting the file, but its not a sticky fix

**Comment by adrian-bio** [comment]
Yes, just add a meta file to it please. It is very annoying

**Comment by zihejia** [comment]
file was removed, sorry about the inconvenience.
