### ISSUE TITLE
Development builds failing on 3.5.1

### ISSUE THREAD

**Issue by CHollasch** [mixpanel/mixpanel-unity#177]
@zihejia with the release of 3.5.1, creating a development build fails to compile.

**Comment by zihejia** [comment]
hi @CHollasch , sorry about that. Could you share the log?

**Comment by vadim-marchuk** [comment]
Same problem here. Below are the compile errors. I see that these properties have been removed in version 3.5.1 but are still in the Controller class within DEVELOPMENT_BUILD preprocessor directives.

Problem 0: ScriptCompileError, DontExtractStacktrace
Library/PackageCache/com.mixpanel.unity@752b5b019c/Mixpanel/Controller.cs(353,37): error CS0117: 'MixpanelStorage' does not contain a definition for 'HasTracked'

Problem 1: ScriptCompileError, DontExtractStacktrace
Library/PackageCache/com.mixpanel.unity@752b5b019c/Mixpanel/Controller.cs(370,33): error CS0117: 'MixpanelStorage' does not contain a definition for 'HasUsedPeople'

**Comment by zihejia** [comment]
@vadim-marchuk @CHollasch , it's been fixed in 3.5.2, sorry gain.
