### ISSUE TITLE
Android. Exception on SDK initialization

### ISSUE THREAD

**Issue by yanmasharski** [mixpanel/mixpanel-unity#18]
We are currently using Mixpanel Unity SDK for all our projects. But we've detected some strange exception on SDK initialization. This happens only on some Android devices. 
 
Our project configuration:
Not modified Mixpanel Unity SDK (v1.0.1) from you repository https://github.com/mixpanel/mixpanel-unity/releases.
Unity 5.5.0f3
Android SDK 25
 
Affected OS versions:
Android OS 4.4.4 / API-19 (KXB21.85-17/23)
Android OS 5.0.2 / API-21 (LRX22G/1649326)
Android OS 5.0.2 / API-21 (LRX22L/1816899)
Android OS 5.1.1 / API-22 (LMY48M/2167285)
Android OS 4.4.4 / API-19 (KXE21.187-42/41)
 
We catched the following exception logs using Unity Performance Reporting service:
 
Exception: JNI: Init'd AndroidJavaObject with null ptr!
UnityEngine.AndroidJavaObject..ctor (IntPtr jobject)
UnityEngine.AndroidJavaObject.AndroidJavaObjectDeleteLocalRef (IntPtr jobject)
UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args)
mixpanel.platform.MixpanelUnityPlatform.get_android_advertising_id ()
mixpanel.platform.MixpanelUnityPlatform.get_distinct_id ()
mixpanel.Mixpanel.Awake ()

**Comment by yanmasharski** [comment]
I've added the next code to GPGSDependencies.cs file, and exception was fixed.

// ADS
            Google.VersionHandler.InvokeInstanceMethod(
                svcSupport, "DependOn",
                new object[]
                {
                    "com.google.android.gms", "play-services-ads",
                    PluginVersion.PlayServicesVersionConstraint
                },
                namedArgs: new Dictionary<string, object>()
                {
                    {"packageIds", new string[] {"extra-google-m2repository"}}
                });

**Comment by mylastgg** [comment]
I am facing the same issue, but I don't have that file. Can you please elaborate your solution? I think it might be promising!

**Comment by yanmasharski** [comment]
You can add the next code to the GPGSDependencies.xml
`    

        <androidPackage spec="com.google.android.gms:play-services-ads:10+">
      <androidSdkPackageIds>
        <androidSdkPackageId>extra-google-m2repository</androidSdkPackageId>
      </androidSdkPackageIds>
      <repositories>
        <repository>https://maven.google.com</repository>
      </repositories>
    </androidPackage>`

**Comment by mylastgg** [comment]
I don't have that file inside the project, is it required?

**Comment by zihejia** [comment]
hi @mylastgg, have you solved your problem?

**Comment by mylastgg** [comment]
@zihejia I "fixed" it by returning immediately after 

`public static string get_android_advertising_id()`

Apparently, this only triggers if Unity Performance Reporting is turned on in Unity.

**Comment by rocktavious** [comment]
2.0 has been released!
