### ISSUE TITLE
Incorrect behaviour with Alias() and Reset()

### ISSUE THREAD

**Issue by VReelTeam** [mixpanel/mixpanel-unity#21]
Following the tips provided by your blog (https://mixpanel.com/blog/2015/09/21/community-tip-maintaining-user-identity/) we Alias() a new user when they sign up and call Reset() when they log out, however we've found issues with both of these functions.

With regards to Alias(), after every call the system seems to incorrectly track the first 1 or 2 events believing they are fired by an Anonymous user rather than the user we've just aliased against! Apart from the behaviour being clearly wrong, these events immediately after sign up can be crucial to understand user patterns.

With regards to Reset(), it simply didn't work as described on the tin, as it instead flushed the entire event queue rather than allocating a new ID. Therefore, we generate our own random GUID when a user logs out and call Identify() with that new ID. Yet, this in itself wasn't particularly reliable either as the next time the app opened, Mixpanel would sometimes believe that the previous user was still logged on, and not the new random GUID. Therefore, we created our own mini saved data in order to track the latest ID between opening and closing the app, and call Identify() whenever the app re-opens.

All of this is (1) a ball-ache, and (2) not how the Mixpanel blog suggests the functions should work. Could someone on the team please take a look at this? I personally enjoy working with Mixpanel and think its a great product, therefore I would hate to have to switch over to one of your competitors.

Thanks in advance!

**Comment by rocktavious** [comment]
@VReelTeam I've rewritten the library to be much more easy to maintain and I beleive this to be fixed in the https://github.com/mixpanel/mixpanel-unity/tree/release/2.0 branch.

**Comment by VolodymyrBS** [comment]
@rocktavious 
Alias() and Reset() methods still has issue in branch 2.0. 
Reset method doesn't modify Distinct Id for next events so its tracked like form previous user.
Also if event will be send too fast after Alias Method new user profile will be created, but after Identify events will be tracked in same user profile that anonymous before sign up. 
you can reproduce it in this test project: https://github.com/VolodymyrBS/MixpanelTest
after you click sign up button in live view you will see "SignUp" from wrong user.

**Comment by rocktavious** [comment]
Hey @VolodymyrBS We made a couple of changes around this in the latest 2.0 branch.  I'm pretty sure Alias, Reset and Identify work as expected now.  There were bugs in each.

**Comment by rocktavious** [comment]
@VolodymyrBS Mixpanel believes that the 2.0 version of the Alias command is doing the correct set of things now but we sometimes still see issues with not being able to search by that alias - they believe it to be a problem on the server side.  

2.0 has been released! So i'm going to close this as there is nothing more we can do on the SDK side.
