### ISSUE TITLE
Unity editor crashes if the Mixpanel component has empty token debug field

### ISSUE THREAD

**Issue by Dakwamine** [mixpanel/mixpanel-unity#26]
Hello,

When the **Debug Token** field is unset in the inspector, Unity hard crashes even if the component is disabled. Is it mandatory to have this field set whichever the component state?

I am using the `1.0.1` version on Unity `2017.1.0f3`.

**Comment by patedit** [comment]
When you run your unity app on debug mode the SDK will use the debug token as the Mixpanel token. If there's no token it will crash :(

**Comment by zihejia** [comment]
Since it's an expected crash, close this one for now.
