### ISSUE TITLE
Missing distinctId API call

### ISSUE THREAD

**Issue by mylastgg** [mixpanel/mixpanel-unity#29]
Hello!

I've noticed that there is no way to retrieve the distinctId from the Unity plugin while that feature is available for iOS and Android native SDKs. I think the distinctId feature is really needed.

**Comment by patedit** [comment]
@mylastgg you are totally right! I can't look into it right now but I'd be very happy to review a PR from you if you feel adventurous !

**Comment by mylastgg** [comment]
@patedit I'd love to contribute but I have little time myself, I'll let you know if and when I can push the PR!

**Comment by rocktavious** [comment]
@mylastgg this is fixed in the 2.0 release branch for this library here - https://github.com/mixpanel/mixpanel-unity/blob/release/2.0/Mixpanel/MixpanelPersistance.cs#L15
