### ISSUE TITLE
Unity Mixpanel SDK is currently incompatible with Universal Windows Platform

### ISSUE THREAD

**Issue by dudugabay** [mixpanel/mixpanel-unity#31]
We develop a Unity VR application which uses MixpanelSDK. 
We need to make a build of the application to run as UWP app and publish it on the Windows Store.
When trying to deploy a unity UWP app package to Windows Store I get the following errors:
![image](https://user-images.githubusercontent.com/15011387/31760677-2787e2b2-b4be-11e7-80e0-a1c034f86922.png)

It there any workaround to use the Mixpanel SDK on UWP?

**Comment by beber666** [comment]
Any reply on this issue ?

**Comment by zihejia** [comment]
We current don't support UWP apps for now. However, we've provided dlls in our latest version, the workaround is to look at Microsoft support docs: "Using a Win32 DLL in a UWP App"
 https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app#BK_Win32DLL

**Comment by rocktavious** [comment]
@dudugabay and @beber666 i've done a full rewrite of the library https://github.com/rocktavious/mixpanel-unity and i'm 99% certain it should fully support Unity + UWP.  If you'd be interested to try it out and validate it works for you it would go a long way to convincing mixpanel to accept my fork and a PR upstream!

**Comment by beber666** [comment]
Hello,

Thanks for your update, but it doesn't work 
Assets/Mixpanel/Mixpanel/Editor/MixpanelSettingsEditor.cs(9,17): error CS0246: The type or namespace name `SettingsProvider' could not be found. Are you missing `System.Configuration' using directive?

Thanks !

**Comment by rocktavious** [comment]
@beber666 what version of unity are you using?  This library is written for Unity 2018.3 or greater

**Comment by rocktavious** [comment]
Should be resolved by branch release/2.0 but unable to test - if someone finds this issue and can test with UWP please reopen this issue
