### ISSUE TITLE
Dispose() function causing hang on exiting app when internet connection is bad.

### ISSUE THREAD

**Issue by chlun1** [mixpanel/mixpanel-unity#35]
This happens on Windows and Mac. I use a tool called Network Link Conditioner on Mac and Clumsy on Windows to simulate a bad internet connection.

When I try to close my application whilst using the above mentioned tools, it takes a long time to close and  the application becomes unresponsive. I have found that it is to do with the Dispose() function called when OnDestroy() is called. More precisely, line 658 in Mixpanel.cs. 

Commenting out the line fixes the slow closing issue but that will probably cause a load of other problems so its not a solution. 

Any suggestions on how to fix this will be appreciated.

Thanks

**Comment by rocktavious** [comment]
@chlun1 not sure if you are still using Mixpanel but i've done a full rewrite of the library https://github.com/rocktavious/mixpanel-unity and if you are willing to test out the new library with the problem you were having to validate its fixed - it would go along way to convincing mixpanel to accept my fork as a PR to the upstream!

**Comment by rocktavious** [comment]
I beleive this to be fixed in the 2.0 release branch @chlun1 if you can report on this let me know otherwise i'll close this out when 2.0 is the officially supported version of the library

**Comment by rocktavious** [comment]
2.0 has been released!
