### ISSUE TITLE
DllNotFoundException when testing in Editor

### ISSUE THREAD

**Issue by Wofiel** [mixpanel/mixpanel-unity#4]
It seems that no MixpanelSDK dll is being shipped in release v1.0.0., as a result, the Editor will fail to pass this point if the Mixpanel component is attached to an object.

```
DllNotFoundException: MixpanelSDK
mixpanel.detail.MixpanelSDKPINVOKE+SWIGExceptionHelper..cctor () (at Assets/Mixpanel/detail/MixpanelSDKPINVOKE.cs:127)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for SWIGExceptionHelper
mixpanel.detail.MixpanelSDKPINVOKE..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for mixpanel.detail.MixpanelSDKPINVOKE
mixpanel.detail.Mixpanel..ctor (System.String token, System.String distinct_id, System.String storage_directory, Boolean enable_log_queue)
mixpanel.Mixpanel.Awake () (at Assets/Mixpanel/Mixpanel.cs:569)
```

**Comment by samgreen** [comment]
Hey @Wofiel, this was an oversight on our release process. Looks like we have some kinks in the process still. 

We plan to release 1.0.1 very soon. In the mean time, I'll see if we can patch the package. Sorry for the inconvenience!

**Comment by samgreen** [comment]
Hey @Wofiel This is resolved in v1.0.1, thanks for your patience!

**Comment by Wofiel** [comment]
That was super quick, thanks so much for the update!

**Comment by samgreen** [comment]
Always happy to help @Wofiel!

**Comment by sharilovav** [comment]
I have same problem with v1.0.1
