### ISSUE TITLE
Android Push Notifications 

### ISSUE THREAD

**Issue by MohHeader** [mixpanel/mixpanel-unity#42]
Hi,

As it is noted : 
~~~
Android push notifications are not supported through this Mixpanel library or through the Unity Notification Services class.
~~~
So I just thought to ask if there are any plans to support it,, is the only solution I have to create my own wrapper around Android SDK ?

**Comment by hivearts** [comment]
Any update on this?

We would like to use mixpanel, but this is really stopping us, since we can't send notifications from mixpanel segments...

**Comment by rocktavious** [comment]
@MohHeader  @galeksic90 unity has added support for push notifications on Android in the "Mobile Notifications" package https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.0/manual/index.html

With the 2.0 release version of this library we should beable to easily add support for this - I will work with @patedit on priority of this after the 2.0 release is shipped.

**Comment by v1adko** [comment]
@rocktavious any update on this? 
Can this be achieved by a bridge to Android SDK?
Any tutorials or case studies would be helpful.

**Comment by v1adko** [comment]
@patedit I've tried creating a Unity plugin using Mixpanel Android SDK, yet I can't get it to work.
Is there a known reason for that or I'm doing something wrong with configuration?

I am willing to contribute as this is quite crucial for us, but I'll need a lot of pointers on how to achieve this within this codebase. Luckily @rocktavious mentioned it shouldn't be hard to do.

**Comment by v1adko** [comment]
For all of the poor souls that have to deal with this, it IS possible to make Mixpanel send push notifications to Android in Unity.

You need to create a plugin wrapper of android SDK and then call it from within C#.

**Comment by Cakku** [comment]
Hey, any info on what's the status of android push support in 2.1? 
I have just upgraded from 1.3 where we had everything working fine and noticed that the format for android push ids registered to Mixpanel has changed. Also there's one open PR #71  that touches the android push id registration, so it's unclear to me if we need to encode the id now, or is the android push registration broken?
