### ISSUE TITLE
Crash at runtime during batch logging event

### ISSUE THREAD

**Issue by acgourley** [mixpanel/mixpanel-unity#43]
This happens during the first batch logging event.

Package version 1.1.1
iOS 11.2.2 on an iPhone 6P 
Unity 2018 beta 4

<img width="1862" alt="screenshot 2018-01-26 19 09 18" src="https://user-images.githubusercontent.com/7680/35468105-789a238e-02cc-11e8-886d-441ee92b24e2.png">

Nothing useful in the logs, even with the mixpanel logging set to trace. It's clear this happens right when a Mixpanel batch operation fires though.

**Comment by acgourley** [comment]
Confirmed the same crash occurs in sample unity application

**Comment by sanboxapps** [comment]
I have the same problem too, any suggestions?

**Comment by zihejia** [comment]
hi @sanboxapps, do you mind to create a simple sample project or steps for how to reproduce? Thanks so much!

**Comment by sanboxapps** [comment]
@zihejia here is a screenshot of the stack trace, it was working before I upgraded to unity 2018.1
I think the update is what caused the problem, I don't even have to log anything, simply starting the app after creating a mixpanel game object with the keys cause it to crash within 30 seconds of the app launch, the same is also happening on andoird
![screen shot 2018-05-08 at 3 41 37 pm](https://user-images.githubusercontent.com/16791082/39786659-5ddf63f6-52d6-11e8-865d-1226c541fb5a.png)

**Comment by zihejia** [comment]
Hi @sanboxapps, thanks for the information. We will get back to you shortly.

**Comment by zihejia** [comment]
We have released a new version v1.2.0 with a fix to this problem, please try again and feel free to reopen it if the same problem still exists.

**Comment by CerebralAriel** [comment]
Also still happening to me with the latest version of the sdk on Unity 2018.1

**Comment by VR-Nima** [comment]
Still happening to us too.  Please advise.

**Comment by zihejia** [comment]
It seems in Unity 2018, it has embedded the same library (mbed TLS) as we do for SSL so it will cause the collision in runtime. We have released a new version 1.3.0 to fix this issue, so close it now. 

https://github.com/mixpanel/mixpanel-unity/releases/tag/v1.3.0
