### ISSUE TITLE
Mac App Store I386 Error

### ISSUE THREAD

**Issue by beber666** [mixpanel/mixpanel-unity#45]
Hi

Just tried to submit a new app but the apple policy changed...
![capture d ecran 2018-03-07 a 15 37 35](https://user-images.githubusercontent.com/6094638/37098178-89977090-221d-11e8-98d0-3a7f4cc99d8a.jpg)

**Comment by zihejia** [comment]
hi @beber666, we have released a new version v1.2.0 with a fix to this problem, please try again and feel free to reopen it if the same problem still exists.

**Comment by beber666** [comment]
Thank you !
