### ISSUE TITLE
Missing dependencies for Windows compilation

### ISSUE THREAD

**Issue by ChimpWorks** [mixpanel/mixpanel-unity#47]
As I was trying to debug issue #28

I attempted to setup the build tools.
You will need:
git, cmake, python, swig

and visual studio 2015 (with cmake tools installed) or change the cmake -G parameter in the build_all.py
to a visual studio 2017 installation with cmake tools installed

this might give a clue as to why the dll is throwing errors, perhaps not all of it's dependencies are available on every system?

Adding this kind of information to the readme would be helpfull.
But I do not have the time to list all the required version numbers.

**Comment by zihejia** [comment]
Hi  @ChimpWorks, we have released a new version v1.2.0 with a fix to windows compilation problem, please try again and feel free to reopen it if the same problem still exists.
