### ISSUE TITLE
Unity 2018 CRASH

### ISSUE THREAD

**Issue by anthonybarouch** [mixpanel/mixpanel-unity#50]
Hello,

Mixpanel crashes on Unity 2018.

I know it's already reported.

But can we have a release date for the fix please?

Thanks a lot.

Best regards,

GAN

**Comment by zihejia** [comment]
hi @anthonybarouch , could you provide more information regarding the crash? Or is the same crash as https://github.com/mixpanel/mixpanel-unity/issues/43?

**Comment by anthonybarouch** [comment]
<img width="2274" alt="capture d ecran 2018-06-27 a 21 01 23" src="https://user-images.githubusercontent.com/5120751/42177992-01f111be-7e2f-11e8-8ab2-acb35ce8499d.png">

seems to be the same. 

Thanks for your quick answer.

Any release date?

Thanks!

**Comment by CerebralAriel** [comment]
Hi. I'm on Unity 2018.1 and this crash is happening to me too. Is there any news on this? We are needing to move forward with our app.
Thanks!

**Comment by VR-Nima** [comment]
@zihejia any word on when this fix will be available?

**Comment by anthonybarouch** [comment]
@VR-Nima for your info, the support team are not aware about this issue... ( support@mixpanel.com )

**Comment by zihejia** [comment]
It seems in Unity 2018, it has embedded the same library (mbed TLS) as we do for SSL so it will cause the collision in runtime. We have released a new version 1.3.0 to fix this issue, so close it now. 

https://github.com/mixpanel/mixpanel-unity/releases/tag/v1.3.0
