### ISSUE TITLE
Log dump at Random times

### ISSUE THREAD

**Issue by wickedcube** [mixpanel/mixpanel-unity#53]
Unity xcode project produces logs like this continously leading to an FPS Drop

MixPanel 1.3.0
Unity 2018.2.0f2

"/Users/zihejia/Documents/Projects/Develop/update-unity/mixpanel-unity/native/source/dependencies/mbedtls/library/ssl_tls.c:3419: 0040:  0b 30 09 06 03 55 04 06 13 02 55 53 31 15 30 13  .0...U....US1.0"

**Comment by zihejia** [comment]
Sorry @wickedcube for the inconvience, would you please re-download 1.3.0 and update it again? Please let me know if any issue.

**Comment by Waserk** [comment]
Hello, I have the same issue, I just downloaded and updated Mixpanel 1.3.0 just a few minutes ago.

**Comment by wickedcube** [comment]
@zihejia i have also tried re-importing MixPanel 1.3.0 ,No change issue still exists
@Waserk please let me know if you find anything, Thanks.

**Comment by zihejia** [comment]
We will release a new version to avoid the confusion, sorry about that

**Comment by wickedcube** [comment]
@zihejia When can we expect the next update ?

**Comment by zihejia** [comment]
@wickedcube working on it now, will release it by today.

**Comment by zihejia** [comment]
We have released a new version v1.3.1. Please try again.

**Comment by zihejia** [comment]
close this one now, please feel free to reopen it if any issue.

**Comment by wickedcube** [comment]
@zihejia  MixPanel.Track() is not tracking anything in version 1.3.1, Can you please check and revert.

**Comment by zihejia** [comment]
Hi @wickedcube, 1.3.1 should work. There is no logging by default but doesn't mean it's not tracking. Could you check if you've used the right Mixpanel token? You could also turn on logging both in Unity and Mixpanel and see if there is any error.
