### ISSUE TITLE
detail::Json::LogicError  operator[] (ArrayIndex): requires arrayValue

### ISSUE THREAD

**Issue by lhejazi** [mixpanel/mixpanel-unity#58]
Hi Mixpanel, 

We are encountering the following error on iOS devices. 

### Stack Trace
```
mixpanel::detail::Json::LogicError · in Json::Value::operator[](ArrayIndex): requires arrayValue
mixpanel::detail::Json::throwLogicError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)    
mixpanel::detail::Json::Value::operator[](unsigned int)  
mixpanel::detail::Json::Value::operator[](int)   
mixpanel::detail::Persistence::dequeue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int)   
mixpanel::detail::Worker::send_batch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) 
mixpanel::detail::Worker::send_track_batch() 
mixpanel::detail::Worker::send_batches() 
mixpanel::detail::Worker::main() 
mixpanel::detail::Worker::Worker(mixpanel::Mixpanel*)::$_0::operator()() const   
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mixpanel::detail::Worker::Worker(mixpanel::Mixpanel*)::$_0> >(void*)   
/usr/lib/system/libsystem_pthread.dylib__pthread_body   
/usr/lib/system/libsystem_pthread.dylib__pthread_start  
/usr/lib/system/libsystem_pthread.dylib_thread_start
```

### Thread Activity

```
mixpanel::detail::Persistence::write(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mixpanel::detail::Json::Value const&)	
mixpanel::Mixpanel::register_(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mixpanel::detail::Json::Value const&)	
CSharp_mixpanelfdetail_Mixpanel_register____	
Classes/Native/Bulk_Assembly-CSharp_11.cpp:21536:2MixpanelSDKPINVOKE_Mixpanel_register__m97DB1352ED329C589D7B910048EDE863787EA425	
Classes/Native/Bulk_Assembly-CSharp_11.cpp:18638:3Mixpanel_register__mF8FD4A2AB43C591E1806ECA614ABA295D01AA3B3
```

### Bug Details

Env | Value
------------ | -------------
Mixpanel Version | v1.3.1
Unity versions affected | 2018.3.7f1, 2018.1.1f1
OS | iOS
Devices | ipad6,  iphone7 Plus, ipad 5, ipad Pro, iphone 6S Plus, iphone 6

### A few notes

1. We never send arrays as property values during event calls or registration. Only non-collection types (int, double, string, etc.)
2. Once a user experiences this the first time, they're highly likely to experience it again, which leads us to believe it persists in caching
3. This seems to be most often first triggered by a user upon app startup.

**Comment by rocktavious** [comment]
Hey @lhejazi 
By any chance would you be willing to switch over to a rewrite i'm doing of this library  -  https://github.com/rocktavious/mixpanel-unity
It will only work on Unity 2018.3 or greater but i think my rewrite (which Mixpanel is entertaining accepting as the new version of the library) will likely fix your problem.  Let me know if you run into any issues setting it up or getting it working either here.

**Comment by lhejazi** [comment]
@rocktavious I've seen your rewrite and this is truly amazing! Kudos and thanks for the undertaking 👏

Discussing with the team whether we give it a go. Will keep you posted!

**Comment by rocktavious** [comment]
@lhejazi Have you had any movement on trying out the 2.0 branch?  Its in better shape then ever and I'd love to close out this issue if the 2.0 branch fixes your problems.  Thanks

**Comment by rocktavious** [comment]
@lhejazi 2.0 has been released!
