### ISSUE TITLE
iOS compile error in Mixpanel.cs

### ISSUE THREAD

**Issue by mdbnet** [mixpanel/mixpanel-unity#67]
Line 74 of Mixpanel.cs should end with a semicolon instead of "}," in order to compile for iOS.

**Comment by rocktavious** [comment]
@mdbnet was this on the new 2.0 release branch?

**Comment by mdbnet** [comment]
Yes.

**Comment by rocktavious** [comment]
@mdbnet fixed https://github.com/mixpanel/mixpanel-unity/commit/bc45c38b530d4f18f96d4e5da68c10fedda76fd9
