### ISSUE TITLE
Crash when flush events

### ISSUE THREAD

**Issue by VolodymyrBS** [mixpanel/mixpanel-unity#72]
Sometimes (steps in unknown) crash happens when new sdk version (from branch release/2.0) flush all queue. 
`ArgumentException: JSON parse error: The document is empty. 
        UnityEngine.JsonUtility.FromJson[T] (System.String json) (at <00000000000000000000000000000000>:0)
        mixpanel.MixpanelManager+d__18.MoveNext () (at <00000000000000000000000000000000>:0)
        UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)
        mixpanel.MixpanelManager.DoFlush (System.String url, mixpanel.queue.PersistentQueue queue) (at <00000000000000000000000000000000>:0)
        mixpanel.MixpanelManager.Flush () (at <00000000000000000000000000000000>:0)
        mixpanel.MixpanelManager+d__11.MoveNext () (at <00000000000000000000000000000000>:0)
        UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)
        mixpanel.MixpanelManager:DoFlush(String, PersistentQueue)
        mixpanel.MixpanelManager:Flush()
        mixpanel.d__11:MoveNext()
        UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)`

**Comment by rocktavious** [comment]
@VolodymyrBS this is related to the invalid/empty json correct?  AFAICT this shouldn't be an issue in the latest 2.0 branch because that shouldn't be able to get into the system.

**Comment by rocktavious** [comment]
2.0 has been released!

**Comment by RedHatJef** [comment]
This is not fixed.  If there is malformed JSON in the locally saved files, mixpanel will crash spectacularly, at boot.  The only fix as a mobile user is to delete the app completely and then reinstall, which is not a great user experience and kills retention numbers.  I've submitted a pull request with this fix.  https://github.com/mixpanel/mixpanel-unity/pull/102
