### ISSUE TITLE
Mixpanel.People.PushDeviceToken not working

### ISSUE THREAD

**Issue by VolodymyrBS** [mixpanel/mixpanel-unity#73]
I'm using release 2.0 branch. 
Push device token not showed in admin panel. 
Also user cannot be found in the messages Target criteria because of this.

**Comment by rocktavious** [comment]
Hey @VolodymyrBS I'm not sure what you are refering too.  According to this [documentation](https://developer.mixpanel.com/docs/unity#section-registering-for-push-notifications) you have to supply the push token (which is different from what we show in the mixpanel settings - the distinct id)

Can you elaborate more on what you are seeing/referring to?

**Comment by VolodymyrBS** [comment]
@rocktavious 
Basicly I mean that Mixpanel.People.PushDeviceToken property not working in new SDK version.
I set Mixpanel.People.PushDeviceToken on device (in real build). I know for sure that this property was set because I made logs in this point. 
But after engage track event there no "Ios Devices" property on user profile in Mixpanel admin panel. Also I can't target this user for push notification because there no push device token saved. Also this property does not appear after a while (I tried to wait for a few days).

P.S. I notice that with old sdk push device token($ios_devices property ) is under "union" section of engage track event data. But in version 2.0 push device this property is under "set" section

**Comment by rocktavious** [comment]
Ya Mixpanel wanted the `ios` prefixes removed from the internal properties - this was a known change but now it should be working (recognizing the internal properties without the prefixes.  Can you please try again?

I will try to ask mixpanel about the `union` vs `set` and see if they know anything about that.

**Comment by patedit** [comment]
Thanks for bringing this up @VolodymyrBS ! This issue is fixed with #80 and will be available in the next release. I'll update this ticket once it's out

**Comment by Abanoub-Emil** [comment]
Could anyone tell me what is the replacement of PushDeviceToken because it gives me a compile error?

Thanks

**Comment by konstantin-gorbunov** [comment]
> Could anyone tell me what is the replacement of PushDeviceToken because it gives me a compile error? `instance.people.addPushDeviceToken(deviceToken). // compile error` Thanks

https://github.com/mixpanel/mixpanel-flutter/issues/3#issuecomment-786425165
Looks like deprecated API

**Comment by jaredmixpanel** [comment]
@konstantin-gorbunov is correct. Mixpanel no longer sends push notifications so there is no use for sending push tokens, you should remove all calls to `addPushDeviceToken`.
