### ISSUE TITLE
API Error: Invalid JSON Encoding

### ISSUE THREAD

**Issue by ellion** [mixpanel/mixpanel-unity#74]
With current HEAD @d267b242122a257a44247928341da43080aa4976 the API connection seems to be broken. I added a verbose=1 and get following response:

`{"error":"data, invalid json encoding","status":0}`

I'm just doing very basic tracking, i.e:

`Mixpanel.Track("level-select" );`

I'm on Win10 x64, Unity 2019.2.5f1

**Comment by rocktavious** [comment]
Hey @ellion Can you give a full stack trace of the error or an example project that is causing the problems?  I just downloaded Unity 2019.2.8f (also on Windows 10 x64) and loaded up the example scene and it works as intended / expected.  So I guess i'm just looking for more information to go off of.

**Comment by ellion** [comment]
Oh wait .. actually the JSON doesn't look right. The time part isn't valid if I'm not mistaken?

```
... "time": 1570709161,80122}}]
```

**Comment by ellion** [comment]
MixpanelValue.ToString() used cultural information for string conversion. In germany 123.45 is noted as 123,45 :) I submitted a pull request to fix this.

**Comment by ellion** [comment]
Okay, it's probably not a good fix, I was a bit too hectic. 

I think it's not a good idea to cut the timestamp's precision, but I can't figure out at what point the double get stringifed with cultural info. I found 3 occurences in MixpanelValue.cs, but even stripping them gives the same result. I will have another look into this later.

(Sorry for spamming this thread)

**Comment by ellion** [comment]
Apparently C# uses local cultural info for stringifying floats and numbers. There still was an implicit conversion in the serialization writer. I updated the pull request and reverted the foregoing changes. This should work for good now and lead to correct conversion with . instead of , on all machines.
