### ISSUE TITLE
Is it possible (if so, how) to track Apple Search Attribution on iOS devices?

### ISSUE THREAD

**Issue by Nesh108** [mixpanel/mixpanel-unity#79]
Hello!

I am trying to figure out how to track the attribution data provided by Apple.
Is it possible to track that through Mixpanel SDK?
I couldn't find anything in the documentation and API.

Thanks :)

**Comment by patedit** [comment]
Hi @Nesh108 - Thanks for writing in! We don't do mobile attribution out of the box in the SDK. However, if you are able to retrieve that information manually, you can use our SDK to track that through an event or a property of an event :)
