### ISSUE TITLE
End of file reached while trying to read queue item on UWP

### ISSUE THREAD

**Issue by daose** [mixpanel/mixpanel-unity#85]
Running into the error: `End of file reached while trying to read queue item` when building a UWP app onto hololens (but not in the editor).

**Update: was able to reproduce this just on a UWP app running on Windows 10, no hololens required**

**Comment by daose** [comment]
Update: was able to reproduce this just on a UWP app running on Windows 10, no hololens required

**Comment by daose** [comment]
more investigation:
- can reproduce on UWP app built for windows 10 using `Examples.unitypackage`.
- on a fresh install the first batch gets sent to mixpanel fine ("Hello From Unity", "event with parameters", "time_it")
- pressing "Track" button results in a "end of file exception" on the next batch.

The first batch had a size of 15122, but after it was sent the next time it tried to read 4707 after the position 15122. However `data.0` still only has a size of 15122 (it didn't write properly?) so it hit "end of file exception" when trying to read it

**Comment by MohHeader** [comment]
@daose were you able to fix that one ?

**Comment by daose** [comment]
Not working on the project anymore, but at the time we just ended up writing our own wrapper over their REST API

Bill

________________________________

**Comment by MohHeader** [comment]
Aha! Thanks for letting me know that.

**Comment by tomkrikorian** [comment]
Having the exact same issue on UWP and Standalone builds using IL2CPP. Anyone found a solution ?

**Comment by BodieHookbang** [comment]
Also having this issue on WebGL builds.

**Comment by tobyg-projectarcher** [comment]
Just ran into this issue as well in Unity on UWP w/ HL2. Doesn't sound from this thread like there's been a fix issued for this yet.

**Comment by zihejia** [comment]
We are working on refactoring the persistence layer to address this issue. Let's use #108 to track.
