### ISSUE TITLE
Error when building: Plugins colliding with each other.

### ISSUE THREAD

**Issue by skryshi** [mixpanel/mixpanel-unity#9]
Got the error below when building the project. Had to remove x86 folder.

```
Plugin 'MixpanelSDK.dll' is used from several locations:
Assets/Plugins/x86/MixpanelSDK.dll would be copied to <PluginPath>/MixpanelSDK.dll
Assets/Plugins/x86_64/MixpanelSDK.dll would be copied to <PluginPath>/MixpanelSDK.dll

Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.HostView:OnGUI()
```

**Comment by samgreen** [comment]
Hi @skryshi, If you remove the x86 folder please be aware that the Mixpanel plugin will no longer function on 32 bit platforms. 

This problem should be solved with the platform settings for the plugin. Can you confirm that your settings match ours? We select which DLL to ship there. See the screenshot below for more information:

![group](https://cloud.githubusercontent.com/assets/276118/16389644/b264a9fe-3c53-11e6-8831-320807b1b5f7.png)

Note that you'll need to change this settings for both `Plugins/x86/Mixpanel.dll` and `Plugins/x86_64/Mixpanel.dll`

Thanks for using the library, please let us know if you encounter any further issues!

**Comment by skryshi** [comment]
My settings do match yours when I get the "Plugins colliding" message. I am on a Mac building for WebGL.

**Comment by hmark** [comment]
I am experiencing same problem with building for Android on Windows (Unity Pro 5.5.1p4).

**Comment by tuncertirnavali** [comment]
Same here,
If you don't want x86 support, just delete the Assets/Plugins/x86/MixpanelSDK.dll and restart Unity.

**Comment by kkumarvm** [comment]
What if am using it for Android ?
should i delete it?

**Comment by delphinius81** [comment]
Have this error when building for iOS through Unity 5.6.2p2 as well. Happens whether I target a universal application or arm64. Unity still tries to copy both dlls. The only way to stop this error is to delete the 32bit version of the dll.

Can you guys rename the 64 bit target and have some kind of dll picker from your shim to load the correctly named file depending on system architecture?

**Comment by rocktavious** [comment]
2.0 has been released!
