### ISSUE TITLE
WebGL freezing on v2.1.0

### ISSUE THREAD

**Issue by shochet** [mixpanel/mixpanel-unity#90]
WebGL is not working in empty project in MixpanelDemo scene.
Freezes as soon as any Mixpanel call is attempted.

Unity 2018.4.13f1
Mixpanel_v210.unitypackage
Built on OS X 10.15.2
Tested on OSX in Safari 13.0.4 and Chrome 79.0.3945.79

Could be because WebGL does not support threads (?)
The only error I see in the javascript console is:

SystemException: Thread creation failed.
UnityLoader.js:4   at System.Threading.Thread.StartInternal (System.Security.Principal.IPrincipal principal, System.Threading.StackCrawlMark& stackMark) [0x00000] in <00000000000000000000000000000000>:0 

I can zip up the unity project if that would be helpful, but it is a new empty project.

**Comment by patedit** [comment]
Hi @shochet - That error is expected since webgl does not support threads but the SDK can handle that case. My suspicious is that persistent storage is not working - I've seen this before. We will take a look. In the meantime, you can contact support@mixpanel.com so this issue is escalated properly. Thank you!

**Comment by shochet** [comment]
Escalated to support. Thanks for taking a look.

**Comment by j1mmie** [comment]
Also running into this. It seems that that mixpanel-unity library requires System.Threading Theads. I don't see a way around using them.

The chain of events is thus:

1. Mixpanel initializes on BeforeSceneLoad, AFAIK this can't be disabled:
https://github.com/mixpanel/mixpanel-unity/blob/master/Mixpanel/Controller.cs#L28

2. GetInstance adds Mixpanel.Controller to the stage
https://github.com/mixpanel/mixpanel-unity/blob/master/Mixpanel/Controller.cs#L47

3. Mixpanel.Controller calls Worker.StartWorkerThread 
https://github.com/mixpanel/mixpanel-unity/blob/master/Mixpanel/Controller.cs#L73

4. Worker.StartWorkerThread starts a System.Threading.Thread:
https://github.com/mixpanel/mixpanel-unity/blob/master/Mixpanel/Worker.cs#L125
